worker_processes auto;
events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/hrms_build;
        index index.html;

        location / {
            try_files $uri /index.html;
        }

        location /assets/ {
            add_header Cache-Control "public, max-age=31536000, immutable";
            types {
                text/javascript  js mjs;
                text/css         css;
            }
        }

        error_page 404 /index.html;
    }
}