const PATH_PREFIX = import.meta.env.VITE_PATH_PREFIX;

export const Routing = {
    Login: `/login`,

    EmployeeDashboard: `${PATH_PREFIX}/dashboard/employee-dashboard`,
    AdminDashboard: `${PATH_PREFIX}/dashboard/admin-dashboard`,
    ForgotPassword: `/forgot-password`,
    OtpVerification: `/otp-verification`,

    Employee: `${PATH_PREFIX}/employee`,
    PersonalDetails: `${PATH_PREFIX}/employee/personal-details`,
    AllEmployees: `${PATH_PREFIX}/employee/all-employees`,
    SingleEmployee: `${PATH_PREFIX}/employee/all-employees/:id`,
    Holidays: `${PATH_PREFIX}/employee/holidays`,
    Attendance: `${PATH_PREFIX}/employee/attendance`,
    WorkLog: `${PATH_PREFIX}/employee/work-log`,
    ResignationEmployee : `${PATH_PREFIX}/employee/employee-resignation`,

    Leaves: `${PATH_PREFIX}/employee/leaves`,
    MyLeaves: `${PATH_PREFIX}/employee/leaves/my-leaves`,

    Projects: `${PATH_PREFIX}/projects`,
    AllProjects: `${PATH_PREFIX}/projects/all-projects`,
    SingleProject: `${PATH_PREFIX}/projects/all-projects/:id`,
    Tasks: `${PATH_PREFIX}/projects/tasks`,
    ProjectStatistics: `${PATH_PREFIX}/projects/project-statistics`,

    PayRoll: `${PATH_PREFIX}/employee/payroll`,
    PaySlipTable: `${PATH_PREFIX}/employee/payroll/payslip`,
    EmployeePaySlip: `${PATH_PREFIX}/employee/payroll/payslip/:id`,
    EmployeeSalary: `${PATH_PREFIX}/hr/payroll/employee-salary`,
    MonthlySalary: `${PATH_PREFIX}/hr/payroll/monthly-salary`,

    HR: `${PATH_PREFIX}/hr`,
    Policies: `${PATH_PREFIX}/hr/policies/all-policies`,
    Inventory: `${PATH_PREFIX}/hr/inventory`,
    OfficeAssetes: `${PATH_PREFIX}/hr/inventory/office-assetes`,
    KitchenAssetes: `${PATH_PREFIX}/hr/inventory/kitchen-assetes`,
    Reports: `${PATH_PREFIX}/hr/reports`,
    LeaveReport: `${PATH_PREFIX}/hr/reports/leave-report`,
    AttendanceReport: `${PATH_PREFIX}/hr/reports/attendance-report`,
    WorkReport: `${PATH_PREFIX}/hr/reports/work-report`,
    WorkReportById: `${PATH_PREFIX}/hr/reports/work-report/:id`,
    ResignationHR: `${PATH_PREFIX}/hr/resignationHR`,
    AllWorkLogs: `${PATH_PREFIX}/hr/workLogs`,
    WorkLogById: `${PATH_PREFIX}/hr/workLogs/:id`,
    Annoncements: `${PATH_PREFIX}/hr/annoncements`,
    RoutePermission: `${PATH_PREFIX}/hr/roles/all-roles/route-permission/:id`,
    AddRoutePermissions: `${PATH_PREFIX}/hr/roles/all-roles/route-permission/add-role`,
    Roles: `${PATH_PREFIX}/hr/roles/all-roles`,
    AllAttendance: `${PATH_PREFIX}/hr/attendance/all-attendance`,
    AttendanceById: `${PATH_PREFIX}/hr/attendance/all-attendance/:id`,
    AllLeaves: `${PATH_PREFIX}/hr/leave/all-leaves`,
    LeaveBalance : `${PATH_PREFIX}/hr/leave/leave-balance`,
    LeaveMaster : `${PATH_PREFIX}/hr/leave/leave-master`,

    Performance: `${PATH_PREFIX}/performance`,
    Goals: `${PATH_PREFIX}/performance/goals`,
    Reviews: `${PATH_PREFIX}/performance/reviews`,
    Assessment: `${PATH_PREFIX}/performance/assessment`,
    EmployeeAssessment: `${PATH_PREFIX}/performance/assessment/employee-assessment`,
    AdminAssessment: `${PATH_PREFIX}/performance/assessment/admin-assessment`,
    EmployeeAssessmentById: `${PATH_PREFIX}/performance/assessment/admin-assessment/employee/:id`,
}
